//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRube.Data.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetRube.Data.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 在实体 {0} 中定义自增主键 的本地化字符串。
        /// </summary>
        internal static string AutoIncrementPKNotFoundException {
            get {
                return ResourceManager.GetString("AutoIncrementPKNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法自动连接实体 {0} 的本地化字符串。
        /// </summary>
        internal static string CanNotAutoJoin {
            get {
                return ResourceManager.GetString("CanNotAutoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法自动将实体 {0} 连接到实体 {1} 的本地化字符串。
        /// </summary>
        internal static string CanNotAutoJoinAs {
            get {
                return ResourceManager.GetString("CanNotAutoJoinAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在实体 {0} 中没有找到名为“{1}”的字段列名 的本地化字符串。
        /// </summary>
        internal static string ColumnNameNotFoundException {
            get {
                return ResourceManager.GetString("ColumnNameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法在查询的结果中分离出 {0} 和 {1} 两个实体 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindSplitPointException {
            get {
                return ResourceManager.GetString("CouldNotFindSplitPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持动态类型 的本地化字符串。
        /// </summary>
        internal static string DynamicTypeNotSupportedException {
            get {
                return ResourceManager.GetString("DynamicTypeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在配置文件中没有找到名为“{0}”的数据源连接设置 的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionStringSettingsException {
            get {
                return ResourceManager.GetString("InvalidConnectionStringSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时没实现 “{0}” 方法 的本地化字符串。
        /// </summary>
        internal static string MethodNotImplementedException {
            get {
                return ResourceManager.GetString("MethodNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持 “{0}” 操作符 的本地化字符串。
        /// </summary>
        internal static string OperatorNotSupportedException {
            get {
                return ResourceManager.GetString("OperatorNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行分页查询时不能直接使用“*”来获取所有字段，必需加上表别名。例如：select t.* from table t order by t.id 的本地化字符串。
        /// </summary>
        internal static string PageQueryAliasException {
            get {
                return ResourceManager.GetString("PageQueryAliasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在实体 {0} 中没有找到名为 “{1}” 的主键 的本地化字符串。
        /// </summary>
        internal static string PKNameNotFoundException {
            get {
                return ResourceManager.GetString("PKNameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在实体中没有找到以“@{0}”命名的属性（在 SQL 语句“{1}”中） 的本地化字符串。
        /// </summary>
        internal static string SqlParamsNotFoundException {
            get {
                return ResourceManager.GetString("SqlParamsNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定了参数“@{0}”，但总共只有 {1} 个参数（在 SQL 语句“{2}”中） 的本地化字符串。
        /// </summary>
        internal static string SqlParamsOutOfRangeException {
            get {
                return ResourceManager.GetString("SqlParamsOutOfRangeException", resourceCulture);
            }
        }
    }
}
